### ISSUE TITLE
Backend Command pipes' paths are not based on the DEVCADE_PATH in the .env file

### ISSUE THREAD

**Issue by matthewlefler** [ComputerScienceHouse/Devcade-onboard#87]
After cloning the repo and setting the .env file up, navigating into the backend folder and running cargo run results in the command pipes being set in the default $HOME/.devcade path rather than the defined DEVCADE_PATH var in the .env file. 

based on what I can understand the front end for the onboard is working as intended, thereby throwing an error when the path in .env is set to something other than the corresponding $HOME/.devcade (in my case DEVCADE_PATH=/home/lefler/.devcade)

Also the backend does not throw a warning when falling back onto the default as wrote in the lib.rs file in the backend folder

current workaround i found was to see where the backend puts the command paths folder and then put the full path of that folder into the .env file

**Comment by Mstrodl** [comment]
Fixed by #88
